### ISSUE TITLE
Arm64 is wrongly compiled

### ISSUE THREAD

**Issue by cutiepoka** [brbeaird/SmartThings-MyQ-Edge#25]
right now if you run the arm 64 version it gives:
```
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/snapshot/server/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1955:46)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.runMain (pkg/prelude/bootstrap.js:1983:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

I am guessing something didn't compile correctly.

If you included a compile command in the package.json I would compile it myself, but I am not sure how you complied it.

On a side note I have tried compling like this and failed. What did you use?

**Comment by 76MavStallion** [comment]
I also get this error:

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/snapshot/server/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1955:46)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.runMain (pkg/prelude/bootstrap.js:1983:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Trying to run on a Raspberri pi with arm64

**Comment by brbeaird** [comment]
@76MavStallion  @cutiepoka I just pushed a fresh one and verified it runs on my pi. Can you try this one?

https://github.com/brbeaird/SmartThings-MyQ-Edge/releases/download/MyQ-Bridge-Server-v1.0.2b/myQBridgeServer-linux-arm64
